version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/product_catalog
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: